export const dataResult = {
  monthlyBudget: 50000,
  bills: [
    {
      id: 1,
      description: 'Dominoes',
      category: 'FoodNDining',
      amount: 430,
      date: '01-02-2020',
    },
    {
      id: 2,
      description: 'Car wash',
      category: 'utility',
      amount: 500,
      date: '02-06-2020',
    },
    {
      id: 3,
      description: 'Amazon',
      category: 'shopping',
      amount: 2030,
      date: '01-07-2020',
    },
    {
      id: 4,
      description: 'House rent',
      category: 'Food & Dining',
      amount: 35900,
      date: '01-03-2020',
    },
    {
      id: 5,
      description: 'Tuition',
      category: 'education',
      amount: 2200,
      date: '01-12-2020',
    },
    {
      id: 6,
      description: 'Amozon Alex',
      category: 'Alex',
      amount: 3000,
      date: '01-14-2020',
    },
    {
      id: 7,
      description: 'Laundry',
      category: 'Personal Care',
      amount: 320,
      date: '01-14-2020',
    },
    {
      id: 8,
      description: 'Laundry',
      category: 'Personal Care',
      amount: 6000,
      date: '01-14-2021',
    },
    {
      id: 9,
      description: 'Two Amozon Alex',
      category: 'Two Personal Care',
      amount: 400,
      date: '02-14-2021',
    },
    {
      id: 10,
      description: 'two Laundry',
      category: 'two Personal Care',
      amount: 600,
      date: '09-14-2021',
    },
    {
      id: 11,
      description: 'Bike',
      category: 'Bike Wash',
      amount: 700,
      date: '12-14-2021',
    },
  ],
};
